---
title: "Building a website with Blogdown and R Markdown"
author: "Simona Simona"
date: 2019-03-06T21:13:14-05:00
categories: ["R"]
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Building a website

It is always a good idea to spread the good news when you come across a fantastic resource to help others and also to give credit to those who have invested enormous amount of time and energy developing it. I made this website in RStudio, an open-source integrated development environment for R, using the blogdown package. I am still rusty in html, CSS and JavaScript, which are the languages commonly used to build websites ground-up. I have limited time to go through the procedure in full. I will thus point you to the wonderful resources that helped me in this process and if you follow them, you will be good to create your own website without my further assistance. The first place to start from is of course familiarising yourself with [RStudio](https://www.rstudio.com/) and the blogdown package which you can read in the [blogdown](https://bookdown.org/yihui/blogdown/) book. You can buy the book if you want but it is also available for free online on that link I have provided. I guess the choice there is pretty obvious for most people. The blogdown package uses [Hugo](https://gohugo.io/) as the website generator. Hugo has plenty of [themes](https://themes.gohugo.io/), which are basically your website designs. You can choose your preferred theme. My website uses the [academic theme](https://themes.gohugo.io/academic/) because as you can tell, it is more suitable for academics and I happen to be one or at least, I am trying to. 

The blogdown book is very clear and accessible but it might not be enough for you, depending on your mirage. You could complement it with a few other online resources. I found write-ups by the co-authors of the book to be very helpful. [Yihui Xie](https://yihui.name/en/) is responsible for the creation of the blogdown package. So, this one you have to know and probably follow on Twitter or anywhere you can find him in online platforms. The answers he gives to questions he is asked on [Stack Overflow](https://stackoverflow.com/), github or his own website could serve you long hours of nightmares. Amber Thomas's blog post about [Making a website using R Markdown](https://amber.rbind.io/blog/2016/12/19/creatingsite/) and Alison Presmanes Hill's talk on [Up & Running with blogdown](https://alison.rbind.io/talk/blogdown-meetup/) are equally nuggets of gold. Check them out. They also provide links to other resources accordingly. [Git](https://git-scm.com/), [Githup](https://github.com/) and [netlify](https://www.netlify.com/) are other platforms you will need. It is better to familiarise yourself with them too.

Other than that I will recommend that you watch three videos on YouTube. The first is by Yihui himself. He pretty much explains the blogdown package in a one hour video. You can find it [here](https://www.youtube.com/watch?v=CjTLN-FXiFA&t=2183s). The second is done by Daniel Quintana. He will show you how to actually setup your website, make changes to the default files and personalise your website. Find the video [here](https://www.youtube.com/watch?v=ox_Ue9yzf-0&t=903s). Finally John Muschelli [here](https://www.youtube.com/watch?v=syWAKaj-4ck). He casually goes through the deployment process, which you will find very useful. He also explains how to include domain names and attaching files to your website. That's all I did for this website to be up. The only other thing you need is your intuition and a bit of some common sense and then you are good to go.
