---
title: "Teaching Research Software and Statistical Programming to Social Science Students: A note to Instructors"
author: "Simona Simona"
date: 2019-07-19T21:13:14-05:00
categories: []
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

**Introduction**

Statistical programming and sofware more generally has become ubiquitous in the social sciences. I think it is fare to say that almost all social science students today will face the need to learn some kind of software at one or two points in their learning journey. The need for software and programming skills in our society has exponentiated in the past decade due to an avalance of data availability. The so called big data revolution is taking the world by storm and the social sciences will not be spared. There are already numerous attempts to bring the social science up to speed with the current tools being used in big data analytics. The consequences of these efforts is the shrinkage of the dividing lines between orthodox disciplines. The need of the hour is to have skills that cater across the disciplines. This means social scientists have to learn some skills typicall in other areas like statistics and computer science and those in other disciplines have to learn some aspects of social sciences. This hybridity has created an environment where everybody or at least those who would want to be counted in the new data dispensation, are on a learning spree. I believe social scientists have a bigger hurdle to learn skills like programming and software than computer scientists or statisticians learning social theory. This post is conceived in this regard. While I have neither the experience nor the right to tell instructors or anybody how to do their job, I have been a student long enough to know that some teaching approches don't just work. This post is directed to me as much as it is to anybody else who is envolved in teaching programming to novice social scientists.

**Teach yourself, dont teach others**. Whenerve you go in class to teach people, the best approach is to imagine you are a student and think about how you would want your teachers to present their materials to you. That way you will not take your role for granted but you will also conentrate and ensure that everybody understands your materials. Well! maybe not everyone but at least a good number or the majority if I can say so. You hve neever been ideal student. You have made do with only 10% of the materials that is presended in class. Giving your students all you have will help them under

**Capturing attention is key**. He who captures the attention of leaners can easily teach them anything. As an instuctor, you are competing with plenty of things in seeking attention from your students. Don't assume that because they have voluntarily turned up or even paid for the session, then they all what to be there. Not necessarily! There are many factors that compel people to register for courses and interest in the course may or may not be one them. Some have registered in order to impress their supervisors or advisors because they suggected the course could be helpful in their data analsysi. Others may be there because they have a training allocation in their studentship budget and they have nothing better to spend their allowance on. Yet others would turn up for training because the course you are offering is mandatory in their programme of choice. They had a failed relationship with mathematics in high school and have spent proceding years avoiding anything that resembles mathematics. Your course is now standing on the way to their most valued degree. They figured a better choice is to close their eyes and drug along hoping to somehow land on softer soil. But even if they are enthusiastic and genuinely interested in learning, they are still not immune to distruction and discouragements especially when a few codes don't seem to    they fancy sitting next to in class. Yet some just do not have anything better to do. Your duty is to make sure that they come of your class with something new they have learne

How can you attract attensition from people. Personability is one of the key elements. Students need to know that you are not some genius who has fallen from extraterrential teritorries. You need to make an extra effort to give them an impression of your struggles as a student. It is fuel for them. They need to relate to the suffering you went through. Because that is only the true. You know how much you have spent sleepless nights to understand that code you speak so fluently now. Let them know that it takes time and that even now you actually dont know everything there is to know in terms of computer programming

**Dont teach students everything you know** Students needs incremental knowledge. Knowledge is cumulative and therefore if you 

** Do not give them a script and walk around like a boss** They probably know how to read better than you do, they certainly didnt come to your class to read the materials on their own. If they wanted to read or if reading the materials could help them, believe it or not you are the last port of entry they would go for. There are plaenty of online materials out there which

